### ISSUE TITLE
make projects and timeline components

### ISSUE THREAD

**Issue by silent-cipher** [BlocSoc-iitr/DappHack#12]
Make component for showing projects submitted under that hackathon
Also, make a component for showing hackathons timeline
these components will be on [hack/[hackName] page](https://github.com/BlocSoc-iitr/DappHack/blob/master/frontend/src/app/hack/%5BhackName%5D/page.js)

**Comment by shivam6862** [comment]
I'm eager to enhance the user experience on the `hack/[hackName]` page by adding two new components:

1. **Projects Component:** Displaying projects submitted under the specific hackathon.
2. **Timeline Component:** Showcasing the timeline of the hackathon.

**Comment by silent-cipher** [comment]
@shivam6862, you can start working on building the components
