### ISSUE TITLE
active link and fixed sidebar

### ISSUE THREAD

**Issue by silent-cipher** [BlocSoc-iitr/DappHack#13]
show which link is active on sidebar by different styling
make sidebar fixed when we scroll through the page
remove scrolling behaviour from project-submission [page](https://github.com/BlocSoc-iitr/DappHack/blob/master/frontend/src/app/hack/%5BhackName%5D/project-submission/page.js) while filling project details

**Comment by shivam6862** [comment]
@me-loser 
@lordshashank 

**I'm eager to contribute! I'll enhance the sidebar with active link styling, implement a fixed sidebar on scroll, and optimize sidebar toggling.**

**Comment by silent-cipher** [comment]
you can work on this issue @shivam6862
