### ISSUE TITLE
Implement changePrizePool correctly

### ISSUE THREAD

**Issue by lordshashank** [BlocSoc-iitr/DappHack#15]
current implementation of [```changePrizePool```](https://github.com/BlocSoc-iitr/DappHack/blob/69ec5d903794061ba270f2548e2a4f80cfd533b0/contracts/contracts/dapphack.sol#L246C1-L294C6) is not optimal. It just increases the prize pool and that also without updating the prize structs. 
Re-implement the function as two functions ```changePoolPrize``` and ```changePrizeArray``` implementing prize changes for sponsors along with updating the relevant structs.

**Comment by yomanthunder** [comment]
I would like to solve the issue

**Comment by lordshashank** [comment]
sure, just make sure to follow the contributing guidlines.

**Comment by yomanthunder** [comment]
@lordshashank as the contract is very big , Contract code size is exceeding exceeds 24576 bytes (a limit introduced in Spurious Dragon) , i have just added one function that was asked to implement in the issue changePrizeArray .
what should i do about it ??

**Comment by lordshashank** [comment]
It would not help in long go, comment out the getter functions for public vars as of now (as public vars have their own getter functions) and implement the team functionality. I guess we would have to shift to interfaces for different functionalities, would keep that for another patch.

**Comment by yomanthunder** [comment]
i think raising a new issue for the teams functionality will be a good idea 
Please do specify how you want to implement the teams feature in that issue
1. **Team Structure:**
 How should teams be structured and created within the contract?
2. **Roles and Permissions:**
 - What roles do you envision within a team, and what permissions should each role have?
4. **Team Interactions:**
5. **Events and Notifications:**

**Comment by yomanthunder** [comment]
And i also want to know what commit convention are you using for this repo ??

**Comment by lordshashank** [comment]
The issue is already there https://github.com/BlocSoc-iitr/DappHack/issues/16 , this issue is independent of that, here our aim is to give an option to sponsor to change the prize distribution in main prize and pool prize, this should be pretty straight forward.

**Comment by yomanthunder** [comment]
@lordshashank, I would greatly appreciate your feedback on my pull request. It's my first contribution, and I'm eager to learn and improve. Please let me know if there are any areas that need attention or if you have any suggestions. Thank you!

**Comment by lordshashank** [comment]
Resolved here https://github.com/BlocSoc-iitr/DappHack/pull/29
