### ISSUE TITLE
implement backend apis for project and team model

### ISSUE THREAD

**Issue by silent-cipher** [BlocSoc-iitr/DappHack#17]
make apis for project and model similar to hackathon or team or user in [controllers directory](https://github.com/BlocSoc-iitr/DappHack/tree/69ec5d903794061ba270f2548e2a4f80cfd533b0/backend/controllers). Don't forget to import these methods in routes [directory](https://github.com/BlocSoc-iitr/DappHack/tree/69ec5d903794061ba270f2548e2a4f80cfd533b0/backend/routes).

APIs must include CRUD operations atleast.

**Comment by shivam6862** [comment]
@silent-cipher 

I'm eager to contribute!

I'll create APIs for projects and models, mirroring the structure of existing hackathon, team, and user controllers in the controllers directory. I'll ensure the inclusion of CRUD operations. Additionally, I'll import these methods into the routes directory for seamless integration.
