### ISSUE TITLE
Upgrade to viem, wagmi from ethers

### ISSUE THREAD

**Issue by silent-cipher** [BlocSoc-iitr/DappHack#19]
Use viem and wagmi to interact with blockchain and run contract functions instead of ethers. Also, update the smart contract function calling to wagmi from react-moralis. With all this you also have to upgrade the wallet connection to [rainbowKit](https://www.rainbowkit.com/docs/installation) or [dynamic](https://docs.dynamic.xyz/introduction/welcome).

**Comment by shivam6862** [comment]
@silent-cipher 

Excited to contribute! Proposing an upgrade to blockchain interactions—switching from ethers to viem and wagmi, and updating smart contract calls from react-moralis to wagmi.
Elevate wallet connectivity with rainbowKit or dynamic for enhanced functionality. Keen to enhance the project with these improvements!
